# Generated by Django 3.0.2 on 2021-03-27 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeBuilderApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='ingredients',
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='')),
                ('ingredients', models.ManyToManyField(to='recipeBuilderApp.Ingredient')),
            ],
        ),
        migrations.AddField(
            model_name='usersettings',
            name='recipes',
            field=models.ManyToManyField(to='recipeBuilderApp.Recipe'),
        ),
    ]
