# Generated by Django 3.0.2 on 2021-04-13 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeBuilderApp', '0002_auto_20210327_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='price',
            field=models.TextField(),
        ),
    ]
